spring:
  kafka:
    bootstrap-servers: localhost:9092
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  topic:
    example: example.t
  measures:
    Paa:
      db-procedure: FETCH_PNL
      publishers:
        publisher1:
          data: topic-data
          notification: topic-notification
        publisher2:
          data: topic-data
          notification: topic-notification
    Pnl:
      db-procedure: FETCH_PNL
      publishers:
        publisher1:
          data: topic-data
          notification: topic-notification
        publisher2:
          data: topic-data
          notification: topic-notification


logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.memorynotfound: DEBUG
    com.tm.example: DEBUG